/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as OurworksRouteImport } from './routes/ourworks'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as TermsAndConditionRouteImport } from './routes/TermsAndCondition'
import { Route as PrivacyPolicyRouteImport } from './routes/PrivacyPolicy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LabsIndexRouteImport } from './routes/labs/index'
import { Route as LabsLabIdRouteImport } from './routes/labs/$labId'

const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const OurworksRoute = OurworksRouteImport.update({
  id: '/ourworks',
  path: '/ourworks',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionRoute = TermsAndConditionRouteImport.update({
  id: '/TermsAndCondition',
  path: '/TermsAndCondition',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/PrivacyPolicy',
  path: '/PrivacyPolicy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsIndexRoute = LabsIndexRouteImport.update({
  id: '/labs/',
  path: '/labs/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsLabIdRoute = LabsLabIdRouteImport.update({
  id: '/labs/$labId',
  path: '/labs/$labId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/PrivacyPolicy': typeof PrivacyPolicyRoute
  '/TermsAndCondition': typeof TermsAndConditionRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/ourworks': typeof OurworksRoute
  '/programs': typeof ProgramsRoute
  '/labs/$labId': typeof LabsLabIdRoute
  '/labs': typeof LabsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/PrivacyPolicy': typeof PrivacyPolicyRoute
  '/TermsAndCondition': typeof TermsAndConditionRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/ourworks': typeof OurworksRoute
  '/programs': typeof ProgramsRoute
  '/labs/$labId': typeof LabsLabIdRoute
  '/labs': typeof LabsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/PrivacyPolicy': typeof PrivacyPolicyRoute
  '/TermsAndCondition': typeof TermsAndConditionRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/ourworks': typeof OurworksRoute
  '/programs': typeof ProgramsRoute
  '/labs/$labId': typeof LabsLabIdRoute
  '/labs/': typeof LabsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/PrivacyPolicy'
    | '/TermsAndCondition'
    | '/about'
    | '/careers'
    | '/contact'
    | '/ourworks'
    | '/programs'
    | '/labs/$labId'
    | '/labs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/PrivacyPolicy'
    | '/TermsAndCondition'
    | '/about'
    | '/careers'
    | '/contact'
    | '/ourworks'
    | '/programs'
    | '/labs/$labId'
    | '/labs'
  id:
    | '__root__'
    | '/'
    | '/PrivacyPolicy'
    | '/TermsAndCondition'
    | '/about'
    | '/careers'
    | '/contact'
    | '/ourworks'
    | '/programs'
    | '/labs/$labId'
    | '/labs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsAndConditionRoute: typeof TermsAndConditionRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  OurworksRoute: typeof OurworksRoute
  ProgramsRoute: typeof ProgramsRoute
  LabsLabIdRoute: typeof LabsLabIdRoute
  LabsIndexRoute: typeof LabsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ourworks': {
      id: '/ourworks'
      path: '/ourworks'
      fullPath: '/ourworks'
      preLoaderRoute: typeof OurworksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/TermsAndCondition': {
      id: '/TermsAndCondition'
      path: '/TermsAndCondition'
      fullPath: '/TermsAndCondition'
      preLoaderRoute: typeof TermsAndConditionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/PrivacyPolicy': {
      id: '/PrivacyPolicy'
      path: '/PrivacyPolicy'
      fullPath: '/PrivacyPolicy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/': {
      id: '/labs/'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof LabsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/$labId': {
      id: '/labs/$labId'
      path: '/labs/$labId'
      fullPath: '/labs/$labId'
      preLoaderRoute: typeof LabsLabIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsAndConditionRoute: TermsAndConditionRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  OurworksRoute: OurworksRoute,
  ProgramsRoute: ProgramsRoute,
  LabsLabIdRoute: LabsLabIdRoute,
  LabsIndexRoute: LabsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
